# Generated by Django 5.1 on 2024-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
